In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [11]:
import os
os.path.exists(r"D:\c ko\Desktop\Data analysis\Teen_Mental_Health_Dataset.csv")#

True

In [12]:
import os
print(os.listdir(r"D:\c ko\Desktop\Data analysis"))

['company.db', 'con esti.pbix', 'consrtruction.sql', 'const.sql', 'cost estimation.xlsx', 'data analysit workplan.docx', 'data analyst resume png.jpg', 'Excel Project Dataset.csv', 'git.docx', 'hello.py', 'kshitiz.ipynb', 'Mysql Syntax Notes.docx', 'nikesh resume data analyst.pdf', 'practice.pbix', 'sales_data.csv.xlsx', 'sql.sql', 'Teen_Mental_Health_Dataset.csv', 'Untitled-1.ipynb', 'Untitled-2.ipynb', 'WhatsApp Image 2026-04-01 at 4.29.18 PM.jpg', 'WhatsApp Image 2026-04-01 at 4.29.18 PM.psd', 'WORKFLOW python.docx', '~$RKFLOW python.docx', '📊 POWER BI DETAILED STEPS.docx', '📒 Pandas Learning Notes.docx', '📘 SQL SYNTAX NOTES WITH EXAMPLES.docx']

In [13]:
import pandas as pd
df=pd.read_csv('Teen_Mental_Health_Dataset.csv')
df.head()
df.describe()
df.isnull().sum()
df

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,18,female,6.8,Instagram,6.6,2.0,2.76,1.0,low,3,4,4,0
1196,16,male,2.3,Both,8.0,1.9,2.12,0.4,high,7,4,4,0
1197,14,female,1.7,Both,8.7,0.7,3.98,0.8,high,1,1,1,0
1198,15,male,3.9,Both,8.5,2.1,3.19,0.6,high,7,9,9,0
1199,16,female,4.7,TikTok,6.5,1.0,2.91,0.9,medium,5,7,3,0

In [14]:
df.dtypes

age                           int64
gender                          str
daily_social_media_hours    float64
platform_usage                  str
sleep_hours                 float64
screen_time_before_sleep    float64
academic_performance        float64
physical_activity           float64
social_interaction_level        str
stress_level                  int64
anxiety_level                 int64
addiction_level               int64
depression_label              int64
dtype: object

In [15]:
df.describe

<bound method NDFrame.describe of       age  gender  daily_social_media_hours platform_usage  sleep_hours  \
0      14    male                       7.9      Instagram          7.4
1      19  female                       1.9         TikTok          8.0
2      17  female                       1.3      Instagram          7.6
3      15    male                       7.4         TikTok          6.9
4      15  female                       4.7           Both          4.9
...   ...     ...                       ...            ...          ...
1195   18  female                       6.8      Instagram          6.6
1196   16    male                       2.3           Both          8.0
1197   14  female                       1.7           Both          8.7
1198   15    male                       3.9           Both          8.5
1199   16  female                       4.7         TikTok          6.5

      screen_time_before_sleep  academic_performance  physical_activity  \
0                          2.9                  3.01                1.5
1                          2.9                  3.22                0.8
2                          0.5                  3.92                0.0
3                          1.6                  3.48                0.8
4                          3.0                  2.37                1.4
...                        ...                   ...                ...
1195                       2.0                  2.76                1.0
1196                       1.9                  2.12                0.4
1197                       0.7                  3.98                0.8
1198                       2.1                  3.19                0.6
1199                       1.0                  2.91                0.9

     social_interaction_level  stress_level  anxiety_level  addiction_level  \
0                         low             2              2                1
1                        high             8              1               10
2                        high             2              4                2
3                      medium             1              7                9
4                      medium             3              5                2
...                       ...           ...            ...              ...
1195                      low             3              4                4
1196                     high             7              4                4
1197                     high             1              1                1
1198                     high             7              9                9
1199                   medium             5              7                3

      depression_label
0                    0
1                    0
2                    0
3                    0
4                    0
...                ...
1195                 0
1196                 0
1197                 0
1198                 0
1199                 0

[1200 rows x 13 columns]>

In [16]:
df.isnull().sum()

age                         0
gender                      0
daily_social_media_hours    0
platform_usage              0
sleep_hours                 0
screen_time_before_sleep    0
academic_performance        0
physical_activity           0
social_interaction_level    0
stress_level                0
anxiety_level               0
addiction_level             0
depression_label            0
dtype: int64

In [17]:
df.columns

Index(['age', 'gender', 'daily_social_media_hours', 'platform_usage',
       'sleep_hours', 'screen_time_before_sleep', 'academic_performance',
       'physical_activity', 'social_interaction_level', 'stress_level',
       'anxiety_level', 'addiction_level', 'depression_label'],
      dtype='str')

In [18]:
df.shape

(1200, 13)

In [19]:
df.value_counts()

age  gender  daily_social_media_hours  platform_usage  sleep_hours  screen_time_before_sleep  academic_performance  physical_activity  social_interaction_level  stress_level  anxiety_level  addiction_level  depression_label
14   male    7.9                       Instagram       7.4          2.9                       3.01                  1.5                low                       2             2              1                0                   1
19   female  1.9                       TikTok          8.0          2.9                       3.22                  0.8                high                      8             1              10               0                   1
17   female  1.3                       Instagram       7.6          0.5                       3.92                  0.0                high                      2             4              2                0                   1
15   male    7.4                       TikTok          6.9          1.6                       3.48                  0.8                medium                    1             7              9                0                   1
     female  4.7                       Both            4.9          3.0                       2.37                  1.4                medium                    3             5              2                0                   1
                                                                                                                                                                                                                                  ..
18   female  6.8                       Instagram       6.6          2.0                       2.76                  1.0                low                       3             4              4                0                   1
16   male    2.3                       Both            8.0          1.9                       2.12                  0.4                high                      7             4              4                0                   1
14   female  1.7                       Both            8.7          0.7                       3.98                  0.8                high                      1             1              1                0                   1
15   male    3.9                       Both            8.5          2.1                       3.19                  0.6                high                      7             9              9                0                   1
16   female  4.7                       TikTok          6.5          1.0                       2.91                  0.9                medium                    5             7              3                0                   1
Name: count, Length: 1200, dtype: int64

In [23]:
df[['age','daily_social_media_hours']].head(10)

   age  daily_social_media_hours
0   14                       7.9
1   19                       1.9
2   17                       1.3
3   15                       7.4
4   15                       4.7
5   19                       7.4
6   18                       2.5
7   16                       4.0
8   19                       3.3
9   15                       1.9

In [ ]:
df.loc[0:6,'age':'sleep_']

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0
5,19,female,7.4,Both,4.4,2.4,2.63,0.6,high,3,5,7,0
6,18,female,2.5,Instagram,6.4,2.4,2.63,0.7,low,2,2,5,0